INSERT INTO `chloedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('1', 'Student and Internship Opportunities', 'https://www.accenture.com/us-en/careers/students-graduates', '1');
INSERT INTO `chloedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('2', 'Hackathon Toolkit', 'https://github.com/GoogleCloudPlatform/hackathon-toolkit', '4');
INSERT INTO `chloedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('3', 'Mux Docs', 'https://docs.mux.com', '6');
INSERT INTO `chloedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('4', 'Download Unity', 'https://store.unity.com/products/unity-personal', '7');
INSERT INTO `chloedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('5', 'Getting Started', 'https://nimbella.com/resources-commander/quickstart', '8');
INSERT INTO `chloedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('6', 'Example Command Sets', 'https://github.com/nimbella/command-sets', '8');
INSERT INTO `chloedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('7', 'Teleportal x HackSC Doc', 'https://docs.google.com/document/d/17pE2tSDCoJhMQQSfSY_DU1jJZPi61pAkvCyQfKXEPdY/edit', '9');
INSERT INTO `chloedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('8', 'Teleportal Docs', 'https://teleportal.dev/docs/', '9');
INSERT INTO `chloedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('9', 'Xmatters Starter Pack', '/static/xmatters.pdf', '10');
INSERT INTO `chloedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('10', 'Help', 'https://help.xmatters.com', '10');
INSERT INTO `chloedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('11', 'Flow Designer', 'https://help.xmatters.com/ondemand/xmodwelcome/flowdesigner/laying-out-flow-designer.htm', '10');
INSERT INTO `chloedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('12', 'API', 'https://help.xmatters.com/xmapi', '10');
INSERT INTO `chloedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('13', 'Docs', 'https://xpring.io/docs#started', '11');
INSERT INTO `chloedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('14', 'Ripple API', 'https://github.com/ripple/xrp-api', '11');

INSERT INTO `jasondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('1', 'Student and Internship Opportunities', 'https://www.accenture.com/us-en/careers/students-graduates', '1');
INSERT INTO `jasondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('2', 'Hackathon Toolkit', 'https://github.com/GoogleCloudPlatform/hackathon-toolkit', '4');
INSERT INTO `jasondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('3', 'Mux Docs', 'https://docs.mux.com', '6');
INSERT INTO `jasondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('4', 'Download Unity', 'https://store.unity.com/products/unity-personal', '7');
INSERT INTO `jasondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('5', 'Getting Started', 'https://nimbella.com/resources-commander/quickstart', '8');
INSERT INTO `jasondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('6', 'Example Command Sets', 'https://github.com/nimbella/command-sets', '8');
INSERT INTO `jasondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('7', 'Teleportal x HackSC Doc', 'https://docs.google.com/document/d/17pE2tSDCoJhMQQSfSY_DU1jJZPi61pAkvCyQfKXEPdY/edit', '9');
INSERT INTO `jasondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('8', 'Teleportal Docs', 'https://teleportal.dev/docs/', '9');
INSERT INTO `jasondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('9', 'Xmatters Starter Pack', '/static/xmatters.pdf', '10');
INSERT INTO `jasondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('10', 'Help', 'https://help.xmatters.com', '10');
INSERT INTO `jasondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('11', 'Flow Designer', 'https://help.xmatters.com/ondemand/xmodwelcome/flowdesigner/laying-out-flow-designer.htm', '10');
INSERT INTO `jasondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('12', 'API', 'https://help.xmatters.com/xmapi', '10');
INSERT INTO `jasondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('13', 'Docs', 'https://xpring.io/docs#started', '11');
INSERT INTO `jasondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('14', 'Ripple API', 'https://github.com/ripple/xrp-api', '11');

INSERT INTO `maxdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('1', 'Student and Internship Opportunities', 'https://www.accenture.com/us-en/careers/students-graduates', '1');
INSERT INTO `maxdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('2', 'Hackathon Toolkit', 'https://github.com/GoogleCloudPlatform/hackathon-toolkit', '4');
INSERT INTO `maxdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('3', 'Mux Docs', 'https://docs.mux.com', '6');
INSERT INTO `maxdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('4', 'Download Unity', 'https://store.unity.com/products/unity-personal', '7');
INSERT INTO `maxdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('5', 'Getting Started', 'https://nimbella.com/resources-commander/quickstart', '8');
INSERT INTO `maxdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('6', 'Example Command Sets', 'https://github.com/nimbella/command-sets', '8');
INSERT INTO `maxdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('7', 'Teleportal x HackSC Doc', 'https://docs.google.com/document/d/17pE2tSDCoJhMQQSfSY_DU1jJZPi61pAkvCyQfKXEPdY/edit', '9');
INSERT INTO `maxdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('8', 'Teleportal Docs', 'https://teleportal.dev/docs/', '9');
INSERT INTO `maxdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('9', 'Xmatters Starter Pack', '/static/xmatters.pdf', '10');
INSERT INTO `maxdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('10', 'Help', 'https://help.xmatters.com', '10');
INSERT INTO `maxdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('11', 'Flow Designer', 'https://help.xmatters.com/ondemand/xmodwelcome/flowdesigner/laying-out-flow-designer.htm', '10');
INSERT INTO `maxdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('12', 'API', 'https://help.xmatters.com/xmapi', '10');
INSERT INTO `maxdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('13', 'Docs', 'https://xpring.io/docs#started', '11');
INSERT INTO `maxdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('14', 'Ripple API', 'https://github.com/ripple/xrp-api', '11');

INSERT INTO `rolanddb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('1', 'Student and Internship Opportunities', 'https://www.accenture.com/us-en/careers/students-graduates', '1');
INSERT INTO `rolanddb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('2', 'Hackathon Toolkit', 'https://github.com/GoogleCloudPlatform/hackathon-toolkit', '4');
INSERT INTO `rolanddb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('3', 'Mux Docs', 'https://docs.mux.com', '6');
INSERT INTO `rolanddb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('4', 'Download Unity', 'https://store.unity.com/products/unity-personal', '7');
INSERT INTO `rolanddb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('5', 'Getting Started', 'https://nimbella.com/resources-commander/quickstart', '8');
INSERT INTO `rolanddb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('6', 'Example Command Sets', 'https://github.com/nimbella/command-sets', '8');
INSERT INTO `rolanddb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('7', 'Teleportal x HackSC Doc', 'https://docs.google.com/document/d/17pE2tSDCoJhMQQSfSY_DU1jJZPi61pAkvCyQfKXEPdY/edit', '9');
INSERT INTO `rolanddb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('8', 'Teleportal Docs', 'https://teleportal.dev/docs/', '9');
INSERT INTO `rolanddb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('9', 'Xmatters Starter Pack', '/static/xmatters.pdf', '10');
INSERT INTO `rolanddb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('10', 'Help', 'https://help.xmatters.com', '10');
INSERT INTO `rolanddb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('11', 'Flow Designer', 'https://help.xmatters.com/ondemand/xmodwelcome/flowdesigner/laying-out-flow-designer.htm', '10');
INSERT INTO `rolanddb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('12', 'API', 'https://help.xmatters.com/xmapi', '10');
INSERT INTO `rolanddb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('13', 'Docs', 'https://xpring.io/docs#started', '11');
INSERT INTO `rolanddb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('14', 'Ripple API', 'https://github.com/ripple/xrp-api', '11');

INSERT INTO `katiedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('1', 'Student and Internship Opportunities', 'https://www.accenture.com/us-en/careers/students-graduates', '1');
INSERT INTO `katiedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('2', 'Hackathon Toolkit', 'https://github.com/GoogleCloudPlatform/hackathon-toolkit', '4');
INSERT INTO `katiedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('3', 'Mux Docs', 'https://docs.mux.com', '6');
INSERT INTO `katiedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('4', 'Download Unity', 'https://store.unity.com/products/unity-personal', '7');
INSERT INTO `katiedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('5', 'Getting Started', 'https://nimbella.com/resources-commander/quickstart', '8');
INSERT INTO `katiedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('6', 'Example Command Sets', 'https://github.com/nimbella/command-sets', '8');
INSERT INTO `katiedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('7', 'Teleportal x HackSC Doc', 'https://docs.google.com/document/d/17pE2tSDCoJhMQQSfSY_DU1jJZPi61pAkvCyQfKXEPdY/edit', '9');
INSERT INTO `katiedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('8', 'Teleportal Docs', 'https://teleportal.dev/docs/', '9');
INSERT INTO `katiedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('9', 'Xmatters Starter Pack', '/static/xmatters.pdf', '10');
INSERT INTO `katiedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('10', 'Help', 'https://help.xmatters.com', '10');
INSERT INTO `katiedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('11', 'Flow Designer', 'https://help.xmatters.com/ondemand/xmodwelcome/flowdesigner/laying-out-flow-designer.htm', '10');
INSERT INTO `katiedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('12', 'API', 'https://help.xmatters.com/xmapi', '10');
INSERT INTO `katiedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('13', 'Docs', 'https://xpring.io/docs#started', '11');
INSERT INTO `katiedb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('14', 'Ripple API', 'https://github.com/ripple/xrp-api', '11');

INSERT INTO `wilsondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('1', 'Student and Internship Opportunities', 'https://www.accenture.com/us-en/careers/students-graduates', '1');
INSERT INTO `wilsondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('2', 'Hackathon Toolkit', 'https://github.com/GoogleCloudPlatform/hackathon-toolkit', '4');
INSERT INTO `wilsondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('3', 'Mux Docs', 'https://docs.mux.com', '6');
INSERT INTO `wilsondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('4', 'Download Unity', 'https://store.unity.com/products/unity-personal', '7');
INSERT INTO `wilsondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('5', 'Getting Started', 'https://nimbella.com/resources-commander/quickstart', '8');
INSERT INTO `wilsondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('6', 'Example Command Sets', 'https://github.com/nimbella/command-sets', '8');
INSERT INTO `wilsondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('7', 'Teleportal x HackSC Doc', 'https://docs.google.com/document/d/17pE2tSDCoJhMQQSfSY_DU1jJZPi61pAkvCyQfKXEPdY/edit', '9');
INSERT INTO `wilsondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('8', 'Teleportal Docs', 'https://teleportal.dev/docs/', '9');
INSERT INTO `wilsondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('9', 'Xmatters Starter Pack', '/static/xmatters.pdf', '10');
INSERT INTO `wilsondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('10', 'Help', 'https://help.xmatters.com', '10');
INSERT INTO `wilsondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('11', 'Flow Designer', 'https://help.xmatters.com/ondemand/xmodwelcome/flowdesigner/laying-out-flow-designer.htm', '10');
INSERT INTO `wilsondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('12', 'API', 'https://help.xmatters.com/xmapi', '10');
INSERT INTO `wilsondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('13', 'Docs', 'https://xpring.io/docs#started', '11');
INSERT INTO `wilsondb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('14', 'Ripple API', 'https://github.com/ripple/xrp-api', '11');

INSERT INTO `testdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('1', 'Student and Internship Opportunities', 'https://www.accenture.com/us-en/careers/students-graduates', '1');
INSERT INTO `testdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('2', 'Hackathon Toolkit', 'https://github.com/GoogleCloudPlatform/hackathon-toolkit', '4');
INSERT INTO `testdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('3', 'Mux Docs', 'https://docs.mux.com', '6');
INSERT INTO `testdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('4', 'Download Unity', 'https://store.unity.com/products/unity-personal', '7');
INSERT INTO `testdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('5', 'Getting Started', 'https://nimbella.com/resources-commander/quickstart', '8');
INSERT INTO `testdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('6', 'Example Command Sets', 'https://github.com/nimbella/command-sets', '8');
INSERT INTO `testdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('7', 'Teleportal x HackSC Doc', 'https://docs.google.com/document/d/17pE2tSDCoJhMQQSfSY_DU1jJZPi61pAkvCyQfKXEPdY/edit', '9');
INSERT INTO `testdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('8', 'Teleportal Docs', 'https://teleportal.dev/docs/', '9');
INSERT INTO `testdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('9', 'Xmatters Starter Pack', '/static/xmatters.pdf', '10');
INSERT INTO `testdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('10', 'Help', 'https://help.xmatters.com', '10');
INSERT INTO `testdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('11', 'Flow Designer', 'https://help.xmatters.com/ondemand/xmodwelcome/flowdesigner/laying-out-flow-designer.htm', '10');
INSERT INTO `testdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('12', 'API', 'https://help.xmatters.com/xmapi', '10');
INSERT INTO `testdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('13', 'Docs', 'https://xpring.io/docs#started', '11');
INSERT INTO `testdb`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('14', 'Ripple API', 'https://github.com/ripple/xrp-api', '11');

INSERT INTO `production`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('1', 'Student and Internship Opportunities', 'https://www.accenture.com/us-en/careers/students-graduates', '1');
INSERT INTO `production`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('2', 'Hackathon Toolkit', 'https://github.com/GoogleCloudPlatform/hackathon-toolkit', '4');
INSERT INTO `production`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('3', 'Mux Docs', 'https://docs.mux.com', '6');
INSERT INTO `production`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('4', 'Download Unity', 'https://store.unity.com/products/unity-personal', '7');
INSERT INTO `production`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('5', 'Getting Started', 'https://nimbella.com/resources-commander/quickstart', '8');
INSERT INTO `production`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('6', 'Example Command Sets', 'https://github.com/nimbella/command-sets', '8');
INSERT INTO `production`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('7', 'Teleportal x HackSC Doc', 'https://docs.google.com/document/d/17pE2tSDCoJhMQQSfSY_DU1jJZPi61pAkvCyQfKXEPdY/edit', '9');
INSERT INTO `production`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('8', 'Teleportal Docs', 'https://teleportal.dev/docs/', '9');
INSERT INTO `production`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('9', 'Xmatters Starter Pack', '/static/xmatters.pdf', '10');
INSERT INTO `production`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('10', 'Help', 'https://help.xmatters.com', '10');
INSERT INTO `production`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('11', 'Flow Designer', 'https://help.xmatters.com/ondemand/xmodwelcome/flowdesigner/laying-out-flow-designer.htm', '10');
INSERT INTO `production`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('12', 'API', 'https://help.xmatters.com/xmapi', '10');
INSERT INTO `production`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('13', 'Docs', 'https://xpring.io/docs#started', '11');
INSERT INTO `production`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('14', 'Ripple API', 'https://github.com/ripple/xrp-api', '11');

INSERT INTO `d4v1qrf33toril`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('1', 'Student and Internship Opportunities', 'https://www.accenture.com/us-en/careers/students-graduates', '1');
INSERT INTO `d4v1qrf33toril`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('2', 'Hackathon Toolkit', 'https://github.com/GoogleCloudPlatform/hackathon-toolkit', '4');
INSERT INTO `d4v1qrf33toril`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('3', 'Mux Docs', 'https://docs.mux.com', '6');
INSERT INTO `d4v1qrf33toril`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('4', 'Download Unity', 'https://store.unity.com/products/unity-personal', '7');
INSERT INTO `d4v1qrf33toril`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('5', 'Getting Started', 'https://nimbella.com/resources-commander/quickstart', '8');
INSERT INTO `d4v1qrf33toril`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('6', 'Example Command Sets', 'https://github.com/nimbella/command-sets', '8');
INSERT INTO `d4v1qrf33toril`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('7', 'Teleportal x HackSC Doc', 'https://docs.google.com/document/d/17pE2tSDCoJhMQQSfSY_DU1jJZPi61pAkvCyQfKXEPdY/edit', '9');
INSERT INTO `d4v1qrf33toril`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('8', 'Teleportal Docs', 'https://teleportal.dev/docs/', '9');
INSERT INTO `d4v1qrf33toril`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('9', 'Xmatters Starter Pack', '/static/xmatters.pdf', '10');
INSERT INTO `d4v1qrf33toril`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('10', 'Help', 'https://help.xmatters.com', '10');
INSERT INTO `d4v1qrf33toril`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('11', 'Flow Designer', 'https://help.xmatters.com/ondemand/xmodwelcome/flowdesigner/laying-out-flow-designer.htm', '10');
INSERT INTO `d4v1qrf33toril`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('12', 'API', 'https://help.xmatters.com/xmapi', '10');
INSERT INTO `d4v1qrf33toril`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('13', 'Docs', 'https://xpring.io/docs#started', '11');
INSERT INTO `d4v1qrf33toril`.`ApiLinks` (`id`, `name`, `link`, `api_id`) VALUES ('14', 'Ripple API', 'https://github.com/ripple/xrp-api', '11');
