
CREATE TABLE MajorEvents (
	id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    isHackathon TINYINT(1) DEFAULT 0,
    start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);